name: Flutter Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Install Flutter SDK
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      # Cache Flutter Dependencies
      - name: Cache Pub Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            flutter/bin/cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 6️⃣ Generate Launcher Icons
      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons:main

      # 7️⃣ Generate Native Splash
      - name: Generate Splash Screen
        run: flutter pub run flutter_native_splash:create

      # 8️⃣ Build Release APK
      - name: Build Release APK
        run: flutter build apk --release

      # 9️⃣ Upload APK Artifact
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
